// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_collect_100_balls_in_gameplay = "CgkI0_r05rgKEAIQHA"; // <GPGSID>
        public const string achievement_run_classic_game_1000_times = "CgkI0_r05rgKEAIQFg"; // <GPGSID>
        public const string achievement_collect_30_balls = "CgkI0_r05rgKEAIQJA"; // <GPGSID>
        public const string achievement_complete_250_levels = "CgkI0_r05rgKEAIQJQ"; // <GPGSID>
        public const string achievement_get_3_____in_1000_lvls = "CgkI0_r05rgKEAIQGQ"; // <GPGSID>
        public const string achievement_get_3_____in_2000_lvls = "CgkI0_r05rgKEAIQGg"; // <GPGSID>
        public const string achievement_buy_10_item_from_shop = "CgkI0_r05rgKEAIQIg"; // <GPGSID>
        public const string achievement_use_ice_power_1000_times = "CgkI0_r05rgKEAIQKw"; // <GPGSID>
        public const string achievement_complete_100_levels = "CgkI0_r05rgKEAIQBA"; // <GPGSID>
        public const string achievement_buy_100_item_from_shop = "CgkI0_r05rgKEAIQIw"; // <GPGSID>
        public const string achievement_collect_10_balls = "CgkI0_r05rgKEAIQEA"; // <GPGSID>
        public const string achievement_use_ice_power_500_times = "CgkI0_r05rgKEAIQKg"; // <GPGSID>
        public const string achievement_play_game_continue_30_days = "CgkI0_r05rgKEAIQMA"; // <GPGSID>
        public const string achievement_complete_game_with_1_move_100_times = "CgkI0_r05rgKEAIQDw"; // <GPGSID>
        public const string achievement_collect_10_balls_in_gameplay = "CgkI0_r05rgKEAIQDA"; // <GPGSID>
        public const string achievement_complete_game_with_1_move_1_time = "CgkI0_r05rgKEAIQAg"; // <GPGSID>
        public const string achievement_use_bomb_power_100_times = "CgkI0_r05rgKEAIQLA"; // <GPGSID>
        public const string leaderboard_multiplayer_champion = "CgkI0_r05rgKEAIQAQ"; // <GPGSID>
        public const string achievement_complete_1000_lvls = "CgkI0_r05rgKEAIQJw"; // <GPGSID>
        public const string achievement_play_multiplayer_10_times = "CgkI0_r05rgKEAIQBg"; // <GPGSID>
        public const string achievement_play_game_continue_60_days = "CgkI0_r05rgKEAIQMQ"; // <GPGSID>
        public const string achievement_share_best_score_on_facebook = "CgkI0_r05rgKEAIQMg"; // <GPGSID>
        public const string achievement_invite_1000_friends = "CgkI0_r05rgKEAIQIQ"; // <GPGSID>
        public const string achievement_play_multiplayer_100_times = "CgkI0_r05rgKEAIQEQ"; // <GPGSID>
        public const string achievement_complete_game_with_1_move_10_times = "CgkI0_r05rgKEAIQDg"; // <GPGSID>
        public const string achievement_win_mp_1000_games = "CgkI0_r05rgKEAIQFA"; // <GPGSID>
        public const string achievement_run_classic_game_100_times = "CgkI0_r05rgKEAIQFQ"; // <GPGSID>
        public const string achievement_use_bomb_power_500_times = "CgkI0_r05rgKEAIQLQ"; // <GPGSID>
        public const string achievement_get_3_____in_100_lvls = "CgkI0_r05rgKEAIQGA"; // <GPGSID>
        public const string achievement_get_3_____in_50_lvls = "CgkI0_r05rgKEAIQFw"; // <GPGSID>
        public const string achievement_play_game_continue_3_days = "CgkI0_r05rgKEAIQDQ"; // <GPGSID>
        public const string achievement_play_game_continue_7_days = "CgkI0_r05rgKEAIQLw"; // <GPGSID>
        public const string achievement_buy_5_item_from_shop = "CgkI0_r05rgKEAIQCQ"; // <GPGSID>
        public const string achievement_use_bomb_power_10_times = "CgkI0_r05rgKEAIQCw"; // <GPGSID>
        public const string achievement_collect_1000_balls_in_gameplay = "CgkI0_r05rgKEAIQHQ"; // <GPGSID>
        public const string achievement_use_bomb_power_1000_times = "CgkI0_r05rgKEAIQLg"; // <GPGSID>
        public const string achievement_get_3_____in_10_lvls = "CgkI0_r05rgKEAIQBQ"; // <GPGSID>
        public const string achievement_run_classic_game_10_times = "CgkI0_r05rgKEAIQBw"; // <GPGSID>
        public const string achievement_invite_3_friends = "CgkI0_r05rgKEAIQCA"; // <GPGSID>
        public const string achievement_get_3_____in_3000_lvls = "CgkI0_r05rgKEAIQGw"; // <GPGSID>
        public const string achievement_play_multiplayer_1000_times = "CgkI0_r05rgKEAIQEg"; // <GPGSID>
        public const string achievement_win_mp_100_games = "CgkI0_r05rgKEAIQEw"; // <GPGSID>
        public const string achievement_collect_10k_balls_in_gameplay = "CgkI0_r05rgKEAIQHg"; // <GPGSID>
        public const string achievement_invite_100_friends = "CgkI0_r05rgKEAIQIA"; // <GPGSID>
        public const string achievement_complete_500_levels = "CgkI0_r05rgKEAIQJg"; // <GPGSID>
        public const string achievement_complete_3000_lvls = "CgkI0_r05rgKEAIQKA"; // <GPGSID>
        public const string achievement_invite_10_friends = "CgkI0_r05rgKEAIQHw"; // <GPGSID>
        public const string achievement_use_ice_power_100_times = "CgkI0_r05rgKEAIQKQ"; // <GPGSID>
        public const string achievement_win_mp_10_games = "CgkI0_r05rgKEAIQAw"; // <GPGSID>
        public const string achievement_use_ice_power_10_times = "CgkI0_r05rgKEAIQCg"; // <GPGSID>

}

